package com.jml.core;

public enum ModelTypes {
    POLYNOMIAL_REGRESSION, LINEAR_REGRESSION, LINEAR_REGRESSION_SGD,
    MULTIPLE_LINEAR_REGRESSION, PERCEPTRON, NEURAL_NETWORK, MULTIPLE_LINEAR_REGRESSION_SGD
}
